apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: world
          persistentVolumeClaim:
            claimName: minecraft-world
      containers:
        - name: minecraft
          image: itzg/minecraft-server:multiarch-latest
          tty: true
          imagePullPolicy: Always
          volumeMounts:
            - name: world
              mountPath: /data
              subPath: minecraft-map
          ports:
            - name: minecraft
              containerPort: 25565
            - name: dynmap
              containerPort: 8123
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: SEED
              value: "4725084288293652062"
            - name: MEMORY 
              value: "2600M"
            - name: ENABLE_JMX
              value: "true"
            - name: USE_AIKAR_FLAGS
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: dynmap
    port: 8123
    protocol: TCP
    targetPort: 8123
  selector:
    app: minecraft
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssd-pv
spec:
  capacity:
    storage: 110Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/ssd
    server: 192.168.0.121
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world
  labels:
    app: minecraft
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 110Gi
